openapi: 3.0.0
info:
  title: 'Slim OpenApi Introduction'
  version: '0.1'
servers:
  -
    url: 'http://localhost:8080'
paths:
  /users:
    get:
      tags:
        - user
      operationId: getUsers
      responses:
        '200':
          description: 'List all users'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
  '/users/{id}':
    get:
      tags:
        - user
      operationId: getUser
      parameters:
        -
          name: id
          in: path
          description: 'User id'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'A single user'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      title: User
      description: 'A simple user model.'
